### ISSUE TITLE
Termux package SciPy import error

### ISSUE THREAD

**Issue by asnelt** [its-pointless/its-pointless.github.io#7]
When I try to use SciPy (version 1.1.0) in termux then I get an import error.
I run 
echo "import scipy.stats as st" | python
and get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/stats/__init__.py", line 345, in <module>
    from .stats import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/stats/stats.py", line 171, in <module>
    from . import distributions
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/stats/distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/stats/_distn_infrastructure.py", line 16, in <module>
    from scipy.misc import doccer
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/misc/__init__.py", line 68, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/interpolate/interpolate.py", line 32, in <module>
    from .interpnd import _ndim_coords_from_arrays
  File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/spatial/__init__.py", line 94, in <module>
    from .kdtree import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/sparse/__init__.py", line 229, in <module>
    from .csr import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/sparse/_sparsetools.cpython-36m.so"...

**Comment by its-pointless** [comment]
My fault, termux updated libc++_shared.so and i didn't get around to
recompiling scipy and numpy. I will get on it now. Thanks for reporting.

On 28 Jun. 2018 3:08 am, "Arno Onken" <notifications@github.com> wrote:

When I try to use SciPy (version 1.1.0) in termux then I get an import
error.
I run
echo "import scipy.stats as st" | python
and get:

Traceback (most recent call last):
File "", line 1, in
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/stats/
*init*.py", line 345, in
from .stats import *
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/stats/stats.py",
line 171, in
from . import distributions
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/stats/distributions.py",
line 10, in
from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/stats/_distn_infrastructure.py",
line 16, in
from scipy.misc import doccer
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/misc/
*init*.py", line 68, in
from scipy.interpolate._pade import pade as _pade
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/interpolate/
*init*.py", line 175, in
from .interpolate import *
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/interpolate/interpolate.py",
line 32, in
from .interpnd import _ndim_coords_from_arrays
File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/spatial/
*init*.py", line 94, in
from .kdtree import *
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/spatial/kdtree.py",
line 8, in
import scipy.sparse
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/sparse/
*init*.py", line 229, in
from .csr import *
File
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/sparse/csr.py",
line 15, in
from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: dlopen failed: cannot locate symbol "_Unwind_Resume"
referenced by
"/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-aarch64.egg/scipy/sparse/_
sparsetools.cpython-36m.so"...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/its-pointless/its-pointless.github.io/issues/7>, or mute
the thread

**Comment by asnelt** [comment]
It works fine now. Thank you very much for addressing this issue so promptly!
