### ISSUE TITLE
ImportError: dlopen failed: library "libopencv_intensity_transform.so.4.4" not found

### ISSUE THREAD

**Issue by huynhtanloc2612** [its-pointless/its-pointless.github.io#71]
Hi,

I installed opencv (version 4.4.0-2) on Termux app (Android) via its-pointless repo. The installation was successfully. However, when I tried to import cv2, below errors occurred. I had tried to find solution on the internet but could not get any solution for this.
Please help take a look on this.

Thanks,

$ python                                                   
Python 3.9.0 (default, Oct  8 2020, 15:54:02)              [Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux                              
Type "help", "copyright", "credits" or "license" for more information.                                                
>>> import cv2                                             
Traceback (most recent call last):                           
File "<stdin>", line 1, in <module>                        
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/cv2/__init__.py", line 96, in <module>                bootstrap()                                              
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/cv2/__init__.py", line 86, in bootstrap               import cv2                                             
ImportError: dlopen failed: library "libopencv_intensity_transform.so.4.4" not found                                  >>>

**Comment by huynhtanloc2612** [comment]
Uninstalling opencv and then executing: pkg install libopencv-contrib. Contrib fixed the issue in my case. Thanks for members of Reddit forum to guide me.
